# Generated by Django 5.2.7 on 2025-10-29 10:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='active_status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
