# Generated by Django 5.2.7 on 2025-10-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
