# Generated by Django 5.2.7 on 2025-10-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_booking_latitude_booking_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='longitude',
        ),
        migrations.AddField(
            model_name='theater',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
