# Generated by Django 5.2.7 on 2025-11-01 07:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cast/')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actor',
            },
        ),
        migrations.CreateModel(
            name='Actress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cast/')),
            ],
            options={
                'verbose_name': 'Actress',
                'verbose_name_plural': 'Actress',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cast/')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Director',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Director', 'Director'), ('Producer', 'Producer'), ('Actor', 'Actor'), ('Actress', 'Actress')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='persons/')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cast/')),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producer',
            },
        ),
        migrations.AddField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(blank=True, to='ticket.actor'),
        ),
        migrations.AddField(
            model_name='movies',
            name='actresses',
            field=models.ManyToManyField(blank=True, to='ticket.actress'),
        ),
        migrations.AddField(
            model_name='movies',
            name='directors',
            field=models.ManyToManyField(blank=True, to='ticket.director'),
        ),
        migrations.AddField(
            model_name='movies',
            name='producers',
            field=models.ManyToManyField(blank=True, to='ticket.producer'),
        ),
    ]
