# Generated by Django 5.2.7 on 2025-11-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_actor_actress_director_person_producer_movies_actors_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='ticket.actor'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='actresses',
            field=models.ManyToManyField(related_name='movies', to='ticket.actress'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='directors',
            field=models.ManyToManyField(related_name='movies', to='ticket.director'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='producers',
            field=models.ManyToManyField(related_name='movies', to='ticket.producer'),
        ),
    ]
