# Generated by Django 5.2.7 on 2025-11-02 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_delete_person_alter_movies_actors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='directors',
        ),
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='ticket.director'),
        ),
    ]
