# Generated by Django 5.2.7 on 2025-11-02 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_remove_movies_directors_movies_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='actresses',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='producers',
        ),
        migrations.AddField(
            model_name='movies',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.actor'),
        ),
        migrations.AddField(
            model_name='movies',
            name='actress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.actress'),
        ),
        migrations.AddField(
            model_name='movies',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.producer'),
        ),
    ]
