# Generated by Django 5.2.7 on 2025-11-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_remove_movies_actors_remove_movies_actresses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='location',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='directors/'),
        ),
    ]
